name: BagIt.NET CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ main ]

jobs:
  macos-build-publish:
    runs-on: macos-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore bagit.net.sln

      - name: Build solution
        run: dotnet build bagit.net.sln --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Unit"

      - name: Run Integration Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Integration"

      - name: Publish macOS ARM64
        run: |
          dotnet publish bagit.net.cli/bagit.net.cli.csproj \
            -c Release \
            -r osx-arm64 \
            --self-contained true \
            --publish-trimmed true \
            -o ./publish/macos-arm64

      - name: Upload macOS ARM64 build
        uses: actions/upload-artifact@v4
        with:
          name: bagit.net-macos-arm64
          path: ./publish/macos-arm64

  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: [9.0.x]

    steps:
      # Step 1: Check out the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      # Step 3: Restore dependencies
      - name: Restore dependencies
        run: dotnet restore bagit.net.sln

      # Step 4: Build solution
      - name: Build
        run: dotnet build bagit.net.sln --no-restore --configuration Release

      # Step 5: Run unit tests
      - name: Run Unit Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Unit"

      # Step 6: Run integration tests
      - name: Run Integration Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Integration"