name: BagIt.NET CI

on:
  push:
    branches: ["release-v*"]
  pull_request:
    branches: [ main ]

jobs:
  windows-build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore bagit.net.sln

      - name: Build
        run: dotnet build bagit.net.sln --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Unit"

      - name: Run Integration Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Integration"
  
  linux-build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore bagit.net.sln

      - name: Build solution
        run: dotnet build bagit.net.sln --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Unit"

      - name: Run Integration Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Integration"

  macos-build-publish:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore bagit.net.sln

      - name: Build solution
        run: dotnet build bagit.net.sln --no-restore --configuration Release

      - name: Run Unit Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Unit"

      - name: Run Integration Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Integration"
    
      - name: Publish macOS ARM64
        run: |
          dotnet publish bagit.net.cli/bagit.net.cli.csproj \
          -c Release \
          -r osx-arm64 \
          /p:SelfContained=false \
          /p:PublishSingleFile=true \
          -o ./publish/macos-arm64

      - name: Upload macOS ARM64 build
        uses: actions/upload-artifact@v4
        with:
          name: bagit.net-macos-arm64
          path: ./publish/macos-arm64