name: BagIt.NET CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: [9.0.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Restore dependencies
        run: dotnet restore bagit.net.sln
      - name: Build
        run: dotnet build bagit.net.sln --no-restore --configuration Release
      - name: Run Unit Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Unit"
      - name: Run Integration Tests
        run: dotnet test bagit.net.tests/bagit.net.tests.csproj --no-build --configuration Release --filter "Category=Integration"

  publish-macos-arm64:
    runs-on: macos-latest
    needs: build-and-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Publish macOS ARM64
        run: |
          dotnet publish bagit.net.cli/bagit.net.cli.csproj \
            -c Release \
            -r osx-arm64 \
            --self-contained true \
            -o ./publish/macos-arm64
      - name: Upload macOS ARM64 build
        uses: actions/upload-artifact@v4
        with:
          name: bagit.net-macos-arm64
          path: ./publish/macos-arm64
